name: Clang Format

on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          find . -name "*.cpp" -o -name "*.h" -o -name "*.hpp" -o -name "*.cxx" | xargs clang-format -style=Google -i

      - name: Check for changes
        id: git_status
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || echo "::set-output name=changed::true"

      - name: Commit and Push if changes
        if: steps.git_status.outputs.changed == 'true'
        run: |
          git commit -m "Automated code formatting with clang-format"
          git push origin HEAD:${{ github.ref }}
